baseURL = "https://blog.ibj.io"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "blog.ibj.io"
theme = "cupper-hugo-theme"
googleAnalytics = "UA-113698885-2"
#disqusShortname = "yourdiscussshortname"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "This is where I hope to write stuff that I find interesting"
  homeMetaContent = "Blog for technology / computer related ramblings"
  footer = "Joe Hirschfeld © 2019"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "January 2, 2006"
  #codePenUser = "someUser"

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/post/"
    weight = 2
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.nav]]
    name = "About"
    url = "https://ibj.io"
    weight = 4
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
