baseURL = "https://blog.ibj.io"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "blog.ibj.io"
theme = "cupper-hugo-theme"
googleAnalytics = "UA-113698885-2"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "<p>Joe Hirschfeld / <a href='https://ibj.io'>ibj.io</a></p><p>This is where I hope to write stuff that I find interesting</p>"
  homeMetaContent = "Blog for technology / computer related ramblings"
  footer = "Joe Hirschfeld / <a href='https://ibj.io'>ibj.io</a> © 2019"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "January 2, 2006"
  #codePenUser = "someUser"

[menu]
  [[menu.nav]]
    name = "Posts"
    url = "/post/"
    weight = 2
  [[menu.nav]]
    name = "About"
    url = "https://ibj.io"
    weight = 4
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
